{% set name = "mediapy" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mediapy-{{ version }}.tar.gz
  sha256: 9b9725838e57fe948777977e7ee2aad4e5e093f9463aacf191f22bfa99a37260

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core
  run:
    - ipython
    - matplotlib-base
    - numpy
    - pillow
    - python >=3.6
    - ffmpeg


test:
  imports:
    - mediapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/mediapy
  summary: Read/write/show images and videos in an IPython notebook
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
