{% set name = "mediapy" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mediapy-{{ version }}.tar.gz
  sha256: 4c85c11c962c3d1a6d8ec4df7c003ad3043d776239a61386a62bf0ca8d57b594

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipython
    - matplotlib-base
    - numpy
    - pillow
    - python >=3.6
    - ffmpeg

test:
  imports:
    - mediapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/mediapy
  summary: Read/write/show images and videos in an IPython notebook
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
