{% set name = "mediapy" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mediapy-{{ version }}.tar.gz
  sha256: bb3f8fbf70ef9a10da8c8a8da428fed87b114fb0e1ecab39cabca18846bc28e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipython
    - matplotlib-base
    - numpy
    - pillow
    - python >=3.6
    - ffmpeg
    - flit-core

test:
  imports:
    - mediapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/mediapy
  summary: Read/write/show images and videos in an IPython notebook
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
